// packages/web-component/src/index.ts
import type { DashboardModel } from '@pebbledash/core';
import type { DomRenderer, WidgetRegistry } from '@pebbledash/renderer-dom';

export class UDDashboard extends HTMLElement {
  #renderer?: DomRenderer;
  #model?: DashboardModel;
  #widgets?: WidgetRegistry;

  set model(m: DashboardModel | undefined) {
    this.#model = m;
    if (this.isConnected && m) {
      this.mount();
    }
  }
  get model() {
    return this.#model;
  }

  /** Registry of widget factories keyed by widget type */
  set widgets(w: WidgetRegistry | undefined) {
    this.#widgets = w;
    // Re-mount if already connected with a model
    if (this.isConnected && this.#model) {
      this.#renderer?.unmount();
      this.mount();
    }
  }
  get widgets() {
    return this.#widgets;
  }

  connectedCallback() {
    this.style.display = 'block';
    if (this.#model) this.mount();
  }

  disconnectedCallback() {
    this.#renderer?.unmount();
    this.#renderer = undefined;
  }

  private async mount() {
    if (!this.#model) return;
    // Import renderer package (dev alias maps to source via Vite in the demo)
    const { DomRenderer } = await import('@pebbledash/renderer-dom');
    this.#renderer = new DomRenderer({
      container: this,
      widgets: this.#widgets,
    });
    this.#renderer.mount(this.#model);
  }
}

customElements.define('ud-dashboard', UDDashboard);

// Re-export widget types for convenience
export type {
  Widget,
  WidgetFactory,
  WidgetRegistry,
  WidgetContext,
} from '@pebbledash/renderer-dom';

// packages/react/src/index.tsx
import { useEffect, useRef } from 'react';
import type { DashboardModel } from '@pebbledash/core';
import type { DomRenderer, WidgetRegistry } from '@pebbledash/renderer-dom';

export interface DashboardProps {
  model: DashboardModel;
  className?: string;
  style?: React.CSSProperties;
  /** Registry of widget factories keyed by widget type */
  widgets?: WidgetRegistry;
}

export function Dashboard({ model, className, style, widgets }: DashboardProps) {
  const ref = useRef<HTMLDivElement>(null);
  const widgetsRef = useRef(widgets);

  // Keep widgets ref updated for stable reference in effect
  useEffect(() => {
    widgetsRef.current = widgets;
  }, [widgets]);

  useEffect(() => {
    if (!ref.current) return;
    let disposed = false;
    let renderer: DomRenderer | undefined;
    (async () => {
      const { DomRenderer: RendererClass } = await import('@pebbledash/renderer-dom');
      if (disposed) return;
      renderer = new RendererClass({
        container: ref.current!,
        widgets: widgetsRef.current,
      });
      renderer.mount(model);
    })();
    return () => {
      disposed = true;
      renderer?.unmount();
    };
  }, [model]);

  const mergedStyle = { width: '100%', height: '100%', ...(style || {}) } as React.CSSProperties;
  return <div ref={ref} className={className} style={mergedStyle} />;
}

// Re-export widget types for convenience
export type {
  Widget,
  WidgetFactory,
  WidgetRegistry,
  WidgetContext,
} from '@pebbledash/renderer-dom';
